### ISSUE TITLE
how to get the model dataType0-epoch45-size256.h5

### ISSUE THREAD

**Issue by jianghongsun** [lzyacht/tongue-diagnosis#2]
hi,I'am very sorry to trouble you.Can you tell me how to get the model  dataType0-epoch45-size256.h5.I 'm look forward to your reply!
Thank you!

**Comment by aislient** [comment]
@jianghongsun 
Do you have the xx.h5 files? I'm look forward to your reply

**Comment by jianghongsun** [comment]
sorry,I don't have that model.
